function FileData_Pairs(x)
{
x.t("csv","object");
x.t("source","name");
x.t("upload","user");
x.t("user","information");
x.t("dialog","box");
x.t("browser","add");
x.t("add","user");
x.t("box","select");
x.t("name","destination");
x.t("name","fields");
x.t("population","tools");
x.t("destination","name");
x.t("fields","upload");
x.t("next","2014");
x.t("select","users");
x.t("2014","zimbra");
x.t("added","source");
x.t("added","users");
x.t("click","next");
x.t("tools","load");
x.t("selecting","users");
x.t("information","using");
x.t("information","manually");
x.t("migrate","click");
x.t("migrate","selecting");
x.t("migrate","users");
x.t("ldap","browser");
x.t("users","dialog");
x.t("users","added");
x.t("users","migrate");
x.t("using","population");
x.t("manually","added");
x.t("load","csv");
x.t("picker","ldap");
x.t("object","picker");
}
