function FileData_Pairs(x)
{
x.t("source","name");
x.t("source","destination");
x.t("dialog","box");
x.t("want","remove");
x.t("list","select");
x.t("list","click");
x.t("add","enter");
x.t("add","users");
x.t("remove","source");
x.t("remove","2014");
x.t("box","click");
x.t("name","optional");
x.t("name","migrate");
x.t("destination","list");
x.t("destination","name");
x.t("select","list");
x.t("2014","zimbra");
x.t("click","add");
x.t("click","remove");
x.t("enter","source");
x.t("selecting","users");
x.t("optional","want");
x.t("migrate","add");
x.t("migrate","destination");
x.t("users","dialog");
x.t("users","migrate");
x.t("users","manually");
x.t("manually","add");
x.t("manually","selecting");
x.t("manually","users");
}
