function FileData_Pairs(x)
{
x.t("csv","file");
x.t("csv","option");
x.t("csv","selecting");
x.t("csv","load");
x.t("user","list");
x.t("dialog","box");
x.t("later","time");
x.t("populate","users");
x.t("time","populate");
x.t("new",".csv");
x.t("file","later");
x.t("file","users");
x.t("file","containing");
x.t("list","new");
x.t("selects","file");
x.t("account","information");
x.t("box","2014");
x.t("box","click");
x.t("2014","zimbra");
x.t("format","save");
x.t("option","selects");
x.t("click","save");
x.t("value","format");
x.t("selecting","users");
x.t("information","comma-separated");
x.t("save","csv");
x.t("save","user");
x.t("migrate","load");
x.t("users","dialog");
x.t("users","migrate");
x.t(".csv","file");
x.t("containing","account");
x.t("load","csv");
x.t("comma-separated","value");
}
