function FileData_Pairs(x)
{
x.t("root","group");
x.t("right","column");
x.t("dialog","box");
x.t("wildcard","filter");
x.t("left","column");
x.t("browser","selects");
x.t("browser","selecting");
x.t("browser","ldap");
x.t("group","left");
x.t("filter","dialog");
x.t("selects","groups");
x.t("name","wildcard");
x.t("box","click");
x.t("select","root");
x.t("select","migrate");
x.t("2014","zimbra");
x.t("populates","accounts");
x.t("groups","accounts");
x.t("enter","name");
x.t("click","2014");
x.t("click","query");
x.t("selecting","users");
x.t("query","right");
x.t("ldap","browser");
x.t("migrate","select");
x.t("migrate","click");
x.t("migrate","ldap");
x.t("users","migrate");
x.t("column","populates");
x.t("column","enter");
x.t("accounts","select");
x.t("accounts","migrate");
}
